# Étape de build
FROM node:16 AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source
COPY . .

# Compiler l'application
RUN npm run build

# Étape de production
FROM nginx:alpine

# Copier les fichiers de build
COPY --from=build /app/build /usr/share/nginx/html

# Exposer le port sur lequel l'application sera disponible
EXPOSE 80

# Commande pour démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
